apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-client-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-client
  template:
    metadata:
      labels:
        app: bookstore-client
    spec:
      containers:
      - image: bookstore-client-container:latest
        name: bookstore-client-container
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: client-config