apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-service
spec:
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
  selector:
    app: bookstore-server-api
  type: LoadBalancer