apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1G
  hostPath:
    path: /mnt/bookstore-data